### ISSUE TITLE
makefile incorrectly includes clean rule in TARGETS

### ISSUE THREAD

**Issue by alesparza** [CIS548/example-code#10]
`clean` should not be done as a TARGET because it defeats the purpose of make only updating code that is modified

https://github.com/CIS548/example-code/blob/a8d3fdecbcceaea1da3ddf9fab017ce197de5822/c-unix-refresher/Makefile#L7

**Comment by nate285** [comment]
Ah ok now I see from the previous comment that it only makes when there is nothing to be modified.
